name: 🔸Auto assign pr
on:
  workflow_dispatch:
    inputs:
      pr_number:
        type: number
        description: "Run workflow for this PR number"
        required: true
      project_id:
        type: number
        description: "Github Project Number"
        required: true
        default: 16
  pull_request:
    types:
      - opened

jobs:
  auto-assign-pr:
    uses: ynput/ops-repo-automation/.github/workflows/pr_to_project.yml@main
    with:
      repo: "${{ github.repository }}"
      project_id: ${{ inputs.project_id || 16 }}
      pull_request_number: ${{ github.event.pull_request.number || inputs.pr_number }}
    secrets:
      token: ${{ secrets.YNPUT_BOT_TOKEN }}
